package com.quantaedge.api;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.security.DigestInputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Locale;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;

/** Private disk-backed recording storage. Keys are generated by the server and never user paths. */
@Service
public class PrivateMediaStorageService {
  public static final long MAX_MEDIA_BYTES = 500L * 1024 * 1024;
  private final Path root;

  public record StoredMedia(String storageKey, String originalFilename, String mediaType,
      long sizeBytes, String sha256) {}

  public PrivateMediaStorageService(
      @Value("${app.media.storage-dir:/var/lib/quantaedge/media}") String storageDirectory) {
    this.root = Path.of(storageDirectory).toAbsolutePath().normalize();
  }

  public StoredMedia store(MultipartFile file) {
    if (file == null || file.isEmpty()) {
      throw badRequest("Choose a recording file to upload.");
    }
    if (file.getSize() > MAX_MEDIA_BYTES) {
      throw badRequest("Recorded classes must be 500 MB or smaller.");
    }
    String declaredType = normalizeType(file.getContentType());
    String originalFilename = safeFilename(file.getOriginalFilename());
    String extension = extensionFor(declaredType);
    String storageKey = UUID.randomUUID() + extension;
    Path target = resolve(storageKey);
    Path temporary = resolve(storageKey + ".part");
    long count = 0;
    try {
      Files.createDirectories(root);
      MessageDigest digest = MessageDigest.getInstance("SHA-256");
      byte[] firstBytes = new byte[16];
      int prefixCount = 0;
      try (InputStream input = file.getInputStream();
           DigestInputStream hashed = new DigestInputStream(input, digest);
           OutputStream output = Files.newOutputStream(temporary,
               StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE)) {
        byte[] buffer = new byte[64 * 1024];
        int read;
        while ((read = hashed.read(buffer)) != -1) {
          if (count + read > MAX_MEDIA_BYTES) {
            throw badRequest("Recorded classes must be 500 MB or smaller.");
          }
          if (prefixCount < firstBytes.length) {
            int take = Math.min(read, firstBytes.length - prefixCount);
            System.arraycopy(buffer, 0, firstBytes, prefixCount, take);
            prefixCount += take;
          }
          output.write(buffer, 0, read);
          count += read;
        }
      }
      String detectedType = detectType(firstBytes, prefixCount, declaredType);
      if (detectedType == null) throw badRequest("The uploaded file is not a supported MP4, WebM, or QuickTime video.");
      if (count < 32) throw badRequest("The uploaded recording is too small to be a valid video.");
      try {
        Files.move(temporary, target, StandardCopyOption.ATOMIC_MOVE);
      } catch (AtomicMoveNotSupportedException ex) {
        Files.move(temporary, target);
      }
      return new StoredMedia(storageKey, originalFilename, detectedType, count,
          HexFormat.of().formatHex(digest.digest()));
    } catch (ResponseStatusException ex) {
      deleteQuietly(temporary);
      throw ex;
    } catch (IOException ex) {
      deleteQuietly(temporary);
      throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "The recording could not be saved.", ex);
    } catch (NoSuchAlgorithmException ex) {
      deleteQuietly(temporary);
      throw new IllegalStateException("SHA-256 is not available.", ex);
    } catch (RuntimeException ex) {
      deleteQuietly(temporary);
      throw ex;
    }
  }

  public Path resolve(String storageKey) {
    if (storageKey == null || !storageKey.matches(
        "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\.(mp4|webm|mov)(\\.part)?")) {
      throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Recording not found.");
    }
    Path result = root.resolve(storageKey).normalize();
    if (!result.startsWith(root)) {
      throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Recording not found.");
    }
    return result;
  }

  public void deleteQuietly(Path path) {
    try {
      Files.deleteIfExists(path);
    } catch (IOException ignored) {
      // A failed cleanup leaves a private orphan, never a public asset.
    }
  }

  private String detectType(byte[] bytes, int length, String declaredType) {
    if ("video/webm".equals(declaredType)
        && length >= 4 && (bytes[0] & 0xff) == 0x1a && (bytes[1] & 0xff) == 0x45
        && (bytes[2] & 0xff) == 0xdf && (bytes[3] & 0xff) == 0xa3) {
      return "video/webm";
    }
    if (("video/mp4".equals(declaredType) || "video/quicktime".equals(declaredType))
        && length >= 8 && bytes[4] == 'f' && bytes[5] == 't' && bytes[6] == 'y' && bytes[7] == 'p') {
      return declaredType;
    }
    return null;
  }

  private String normalizeType(String contentType) {
    String type = contentType == null ? "" : contentType.split(";", 2)[0].trim().toLowerCase(Locale.ROOT);
    if (!type.equals("video/mp4") && !type.equals("video/webm") && !type.equals("video/quicktime")) {
      throw badRequest("Use an MP4, WebM, or QuickTime video recording.");
    }
    return type;
  }

  private String extensionFor(String type) {
    return switch (type) {
      case "video/mp4" -> ".mp4";
      case "video/webm" -> ".webm";
      case "video/quicktime" -> ".mov";
      default -> throw badRequest("Unsupported recording format.");
    };
  }

  private String safeFilename(String original) {
    if (original == null || original.isBlank()) return "recording.mp4";
    String name = original.replace('\\', '/');
    name = name.substring(name.lastIndexOf('/') + 1).trim();
    name = name.replaceAll("[^A-Za-z0-9._() -]", "_");
    if (name.isBlank()) return "recording.mp4";
    return name.length() > 255 ? name.substring(name.length() - 255) : name;
  }

  private ResponseStatusException badRequest(String message) {
    return new ResponseStatusException(HttpStatus.BAD_REQUEST, message);
  }
}
