'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
type Row={class_code:string;class_name:string;subject_code:string;subject_name:string;chapter_id:number|null;chapter_code:string|null;chapter_name:string|null;chapter_description:string|null;chapter_sort_order:number|null;chapter_status:string|null;chapter_active:boolean|null;lesson_id:number|null;lesson_code:string|null;lesson_title:string|null;lesson_summary:string|null;estimated_minutes:number|null;lesson_sort_order:number|null;lesson_status:string|null;lesson_active:boolean|null;block_count:number|null;question_count:number|null};
type Selection={type:'chapter'|'lesson';id:number};
const empty={displayName:'',description:'',chapterStatus:'DRAFT',chapterSortOrder:1,title:'',summary:'',estimatedMinutes:10,lessonStatus:'DRAFT',sortOrder:1};
function parsed(v:unknown,fallback:any=[]){if(typeof v!=='string')return v??fallback;try{return JSON.parse(v)}catch{return fallback}}
async function api(url:string,token:string,init:RequestInit={}){const headers=new Headers(init.headers||{});if(token)headers.set('X-Admin-Token',token);if(init.body)headers.set('Content-Type','application/json');const r=await fetch(url,{...init,headers,cache:'no-store'});const raw=await r.text();let d:any={};try{d=raw?JSON.parse(raw):{}}catch{d={message:raw}}if(!r.ok)throw new Error(d.detail||d.message||d.error||('Request failed ('+r.status+')'));return d}
export default function AdminHome(){
 const [rows,setRows]=useState<Row[]>([]),[token,setToken]=useState(''),[activeToken,setActiveToken]=useState('');
 const [cls,setCls]=useState('ALL'),[sub,setSub]=useState('ALL'),[status,setStatus]=useState('ALL'),[search,setSearch]=useState('');
 const [sel,setSel]=useState<Selection|null>(null),[detail,setDetail]=useState<any>(null),[form,setForm]=useState<any>(empty);
 const [blocks,setBlocks]=useState('[]'),[questions,setQuestions]=useState('[]'),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(secret:string){setLoading(true);setError('');try{const data=await api('/api/v1/admin/content',secret) as Row[];setRows(data);setToken(secret);setActiveToken(secret)}catch(e){setError(e instanceof Error?e.message:'Library load failed')}finally{setLoading(false)}}
 async function open(item:Selection){setSel(item);setDetail(null);setError('');setNotice('');try{const d=await api('/api/v1/admin/content/'+(item.type==='chapter'?'chapters':'lessons')+'/'+item.id,activeToken);setDetail(d);setForm(item.type==='chapter'?{...empty,displayName:d.chapter_name||'',description:d.chapter_description||'',chapterStatus:d.chapter_status||'DRAFT',chapterSortOrder:Number(d.chapter_sort_order||1)}:{...empty,displayName:d.chapter_name||'',description:d.chapter_description||'',chapterStatus:d.chapter_status||'DRAFT',chapterSortOrder:Number(d.chapter_sort_order||1),title:d.lesson_title||'',summary:d.lesson_summary||'',estimatedMinutes:Number(d.estimated_minutes||10),lessonStatus:d.lesson_status||'DRAFT',sortOrder:Number(d.lesson_sort_order||1)});setBlocks(JSON.stringify((d.blocks||[]).map((b:any)=>({...b,content:parsed(b.content,{})})),null,2));setQuestions(JSON.stringify((d.questions||[]).map((q:any)=>({...q,options:parsed(q.options,[])})),null,2))}catch(e){setError(e instanceof Error?e.message:'Could not open content')}}
 useEffect(()=>{void load('')},[]);
 const filtered=useMemo(()=>rows.filter(r=>{if(cls!=='ALL'&&r.class_code!==cls)return false;if(sub!=='ALL'&&r.subject_code!==sub)return false;const n=search.trim().toLocaleLowerCase();return !n||[r.class_name,r.subject_name,r.chapter_name||'',r.lesson_title||'',r.chapter_code||'',r.lesson_code||''].some(v=>v.toLocaleLowerCase().includes(n))}),[rows,cls,sub,search]);
 const groups=useMemo(()=>{const m=new Map<number,Row[]>();filtered.forEach(r=>{if(r.chapter_id!==null){const g=m.get(r.chapter_id)||[];g.push(r);m.set(r.chapter_id,g)}});return Array.from(m.entries()).filter(([,g])=>status==='ALL'||g[0].chapter_status===status||g.some(r=>r.lesson_status===status))},[filtered,status]);
 const classes=Array.from(new Map(rows.map(r=>[r.class_code,r.class_name])).entries());
 const subjects=Array.from(new Map(rows.filter(r=>cls==='ALL'||r.class_code===cls).map(r=>[r.subject_code,r.subject_name])).entries());
 const lessonRows=rows.filter(r=>r.lesson_id!==null);
 async function saveChapter(nextStatus?:string){if(!sel||sel.type!=='chapter')return;setSaving(true);setError('');setNotice('');try{await api('/api/v1/admin/content/chapters/'+sel.id,activeToken,{method:'PATCH',body:JSON.stringify({displayName:form.displayName,description:form.description,status:nextStatus||form.chapterStatus,sortOrder:Number(form.chapterSortOrder)})});setNotice('Chapter saved.');await load(activeToken);await open(sel)}catch(e){setError(e instanceof Error?e.message:'Chapter save failed')}finally{setSaving(false)}}
 async function saveLesson(nextStatus?:string){if(!sel||sel.type!=='lesson')return;setSaving(true);setError('');setNotice('');try{const b=JSON.parse(blocks),q=JSON.parse(questions);if(!Array.isArray(b)||!Array.isArray(q))throw new Error('Blocks and questions must be JSON arrays.');await api('/api/v1/admin/content/lessons/'+sel.id,activeToken,{method:'PATCH',body:JSON.stringify({title:form.title,summary:form.summary,estimatedMinutes:Number(form.estimatedMinutes),status:nextStatus||form.lessonStatus,sortOrder:Number(form.sortOrder),blocks:b,questions:q})});setNotice('Lesson and content saved.');await load(activeToken);await open(sel)}catch(e){setError(e instanceof Error?e.message:'Lesson save failed')}finally{setSaving(false)}}
 return <main className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="admin-brand"><span className="brand-mark">Q</span><span><strong>Quanta</strong>Edge<small>ADMIN</small></span></Link><nav><span className="nav-label">WORKSPACE</span><a href="#top" className="active">▦ Dashboard</a><a href="#content">▤ Content library</a><a href="#editor">✎ Edit & publish</a></nav><div className="admin-user"><span className="avatar">Q</span><div><strong>Content operator</strong><small>QuantaEdge</small></div></div></aside>
 <section className="admin-main" id="top"><header className="admin-top admin-top-content"><div><span className="admin-kicker">QUANTAEDGE LEARNING</span><h1>Curriculum & content operations</h1><p>Class और subject wise content को देखें, बदलें और publish करें।</p></div><div className="top-status"><span className="status-dot"/>{loading?'Loading':'Content API'}</div></header>
 <section className="admin-access"><div><strong>Content access</strong><p>Local preview में token की जरूरत नहीं। Production में configured admin token डालें; यह browser storage में save नहीं होता।</p></div><div className="admin-token-control"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Admin token (production)" aria-label="Admin content token"/><button type="button" disabled={loading} onClick={()=>void load(token)}>Connect / Refresh</button></div></section>
 {error&&<div className="admin-alert" role="alert">{error}</div>}{notice&&<div className="admin-notice" role="status">{notice}</div>}
 <div className="admin-grid stats"><article><span>Classes</span><strong>{classes.length}</strong><small>curriculum classes</small></article><article><span>Class-subject tracks</span><strong>{new Set(rows.map(r=>r.class_code+'|'+r.subject_code)).size}</strong><small>Maths and Science</small></article><article><span>Chapters</span><strong>{new Set(rows.map(r=>r.chapter_id).filter(x=>x!==null)).size}</strong><small>including unpublished</small></article><article><span>Published lessons</span><strong>{lessonRows.filter(r=>r.lesson_status==='PUBLISHED'&&r.lesson_active&&r.chapter_status==='PUBLISHED'&&r.chapter_active===true).length}</strong><small>{lessonRows.length} total lessons</small></article></div>
 <div className="library-layout" id="content"><section className="admin-panel library-panel"><div className="panel-head"><div><span>CONTENT LIBRARY</span><h2>All classes · all subjects</h2></div><span className="count">{filtered.length} rows</span></div>
 <div className="library-filters"><label>Class<select value={cls} onChange={e=>{setCls(e.target.value);setSub('ALL')}}><option value="ALL">All classes</option>{classes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Subject<select value={sub} onChange={e=>setSub(e.target.value)}><option value="ALL">All subjects</option>{subjects.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="PUBLISHED">Published</option><option value="DRAFT">Draft / unpublished</option><option value="REVIEW">Review</option><option value="ARCHIVED">Archived</option></select></label><label className="library-search">Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Chapter or lesson name"/></label></div>
 <div className="library-list">{loading&&rows.length===0?<div className="library-empty">Content library load हो रही है…</div>:groups.length===0?<div className="library-empty">इन filters में content नहीं मिला।</div>:groups.map(([id,g])=>{const ch=g[0],ls=g.filter(r=>r.lesson_id!==null&&(status==='ALL'||ch.chapter_status===status||r.lesson_status===status));return <div className="library-chapter" key={id}><button className={'library-chapter-head '+(sel?.type==='chapter'&&sel.id===id?'selected':'')} type="button" onClick={()=>void open({type:'chapter',id})}><span className="library-chapter-icon">▤</span><span className="library-item-main"><strong>{ch.chapter_name||'Untitled chapter'}</strong><small>{ch.class_name} · {ch.subject_name} · {ls.length} lessons shown</small></span><span className={'status-pill '+String(ch.chapter_status||'DRAFT').toLowerCase()}>{ch.chapter_status||'DRAFT'}</span><span className="library-arrow">→</span></button>{ls.map(r=><button key={r.lesson_id} type="button" className={'library-lesson '+(sel?.type==='lesson'&&sel.id===r.lesson_id?'selected':'')} onClick={()=>void open({type:'lesson',id:Number(r.lesson_id)})}><span className="lesson-list-mark">↳</span><span className="library-item-main"><strong>{r.lesson_title||'Untitled lesson'}</strong><small>{r.estimated_minutes||0} min · {r.block_count||0} blocks · {r.question_count||0} questions</small></span><span className={'status-pill '+String(r.lesson_status||'DRAFT').toLowerCase()}>{r.lesson_status||'DRAFT'}</span><span className="library-arrow">→</span></button>)}</div>})}</div></section>
 <section className="admin-panel editor-panel" id="editor">{!sel||!detail?<div className="editor-empty"><div className="editor-empty-mark">✎</div><h2>Choose content to edit</h2><p>Chapter या lesson चुनें। Draft और archived content भी library में उपलब्ध है।</p></div>:<div className="editor-content">
 <div className="panel-head"><div><span>{sel.type==='chapter'?'CHAPTER EDITOR':'LESSON EDITOR'}</span><h2>{sel.type==='chapter'?detail.chapter_name:detail.lesson_title}</h2></div><span className="count">{detail.class_name} · {detail.subject_name}</span></div><div className="editor-context"><span>कक्षा {detail.class_code}</span><span>{detail.subject_name}</span><span>{detail.chapter_name}</span></div>{sel.type==='lesson'&&detail.chapter_status!=='PUBLISHED'&&<div className="admin-alert" role="note">यह lesson छात्र को दिखाई नहीं देगा जब तक इसका parent chapter Published न हो।</div>}
 {sel.type==='chapter'?<><label className="editor-field">Chapter name<input maxLength={160} value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label className="editor-field">Description<textarea rows={4} maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="editor-two-col"><label className="editor-field">Status<select value={form.chapterStatus} onChange={e=>setForm({...form,chapterStatus:e.target.value})}><option value="DRAFT">Draft / unpublished</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></label><label className="editor-field">Chapter order<input type="number" min={1} max={10000} value={form.chapterSortOrder} onChange={e=>setForm({...form,chapterSortOrder:Number(e.target.value)})}/></label></div><div className="editor-actions"><button type="button" disabled={saving} onClick={()=>void saveChapter()}>{saving?'Saving…':'Save chapter'}</button><button type="button" className="secondary-action" disabled={saving} onClick={()=>void saveChapter(form.chapterStatus==='PUBLISHED'?'DRAFT':'PUBLISHED')}>{form.chapterStatus==='PUBLISHED'?'Unpublish chapter':'Publish chapter'}</button></div></>:<>
 <label className="editor-field">Lesson title<input maxLength={240} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="editor-field">Summary<textarea rows={3} maxLength={800} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><div className="editor-two-col"><label className="editor-field">Minutes<input type="number" min={1} max={120} value={form.estimatedMinutes} onChange={e=>setForm({...form,estimatedMinutes:Number(e.target.value)})}/></label><label className="editor-field">Status<select value={form.lessonStatus} onChange={e=>setForm({...form,lessonStatus:e.target.value})}><option value="DRAFT">Draft / unpublished</option><option value="REVIEW">Review</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></label></div><label className="editor-field">Lesson order<input type="number" min={1} max={10000} value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:Number(e.target.value)})}/></label><details className="json-editor"><summary>Learning blocks · JSON editor ({(detail.blocks||[]).length})</summary><p>Each entry contains sequence_no, block_type and a content JSON object.</p><textarea spellCheck={false} value={blocks} onChange={e=>setBlocks(e.target.value)} rows={12}/></details><details className="json-editor"><summary>Practice questions · JSON editor ({(detail.questions||[]).length})</summary><p>Preserve existing question IDs. Set active=false to hide a question while preserving history.</p><textarea spellCheck={false} value={questions} onChange={e=>setQuestions(e.target.value)} rows={12}/></details><div className="editor-actions"><button type="button" disabled={saving} onClick={()=>void saveLesson()}>{saving?'Saving…':'Save lesson & content'}</button><button type="button" className="secondary-action" disabled={saving} onClick={()=>void saveLesson(form.lessonStatus==='PUBLISHED'?'DRAFT':'PUBLISHED')}>{form.lessonStatus==='PUBLISHED'?'Unpublish lesson':'Publish lesson'}</button></div></>}
 <p className="editor-footnote">Class/subject mapping stays tied to the curriculum. Students see content only when its chapter and lesson are published.</p></div>}</section></div>
 <footer className="admin-footer">QuantaEdge Admin · PostgreSQL-backed content · Local preview student remains local-only</footer></section></main>;
}