-- V14: add source registry, curriculum audit contracts, structured answers,
-- and stop serving generated lesson shells as if they were complete teaching content.

alter table question
  add column if not exists marks integer,
  add column if not exists exam_format varchar(40),
  add column if not exists topic varchar(200),
  add column if not exists subtopic varchar(200),
  add column if not exists skill varchar(200),
  add column if not exists answer_payload jsonb not null default '{}'::jsonb;

alter table question drop constraint if exists question_question_type_check;
alter table question add constraint question_question_type_check
  check (question_type in (
    'MCQ','TRUE_FALSE','INPUT','MATCH','ORDER','ASSERTION_REASON',
    'CASE_BASED','SHORT_ANSWER','LONG_ANSWER','NUMERICAL','SOURCE_BASED'
  ));

create table if not exists content_source (
  id bigint generated by default as identity primary key,
  source_kind varchar(40) not null,
  title varchar(300) not null,
  provider varchar(200),
  source_url text,
  edition varchar(160) not null default 'UNVERIFIED',
  language varchar(20) not null default 'hi',
  source_year integer,
  checksum varchar(64),
  status varchar(30) not null default 'REFERENCE',
  accessed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_kind,title,edition)
);

create table if not exists chapter_source (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references curriculum_chapter(id) on delete cascade,
  source_id bigint not null references content_source(id) on delete restrict,
  source_chapter_no integer,
  coverage_status varchar(30) not null default 'NEEDS_REVIEW',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(chapter_id,source_id)
);

create table if not exists chapter_concept (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references curriculum_chapter(id) on delete cascade,
  code varchar(100) not null,
  title varchar(240) not null,
  description text,
  concept_order integer not null default 1,
  status varchar(30) not null default 'AUTHORING_REQUIRED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(chapter_id,code),
  check(status in ('AUTHORING_REQUIRED','DRAFT','REVIEW','READY_FOR_REVIEW','PUBLISHED','ARCHIVED'))
);

create table if not exists lesson_requirement (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references curriculum_chapter(id) on delete cascade,
  requirement_code varchar(80) not null,
  description varchar(500) not null,
  min_count integer not null default 1,
  required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(chapter_id,requirement_code),
  check(min_count >= 0)
);

create index if not exists idx_content_source_status on content_source(status,source_kind);
create index if not exists idx_chapter_source_coverage on chapter_source(chapter_id,coverage_status);
create index if not exists idx_chapter_concept_chapter_status on chapter_concept(chapter_id,status);
create index if not exists idx_lesson_requirement_chapter_required on lesson_requirement(chapter_id,required);

create or replace function strip_answer_keys(value jsonb)
returns jsonb
language sql
immutable
parallel safe
as $$
  select case jsonb_typeof(value)
    when 'object' then (
      select coalesce(jsonb_object_agg(e.key, strip_answer_keys(e.value)), '{}'::jsonb)
      from jsonb_each(value) as e(key,value)
      where e.key not in (
        'correctOption','correct','is_correct','answer','answer_payload',
        'answerKey','correct_answer','solution'
      )
    )
    when 'array' then (
      select coalesce(jsonb_agg(strip_answer_keys(a.value)), '[]'::jsonb)
      from jsonb_array_elements(value) as a(value)
    )
    else value
  end
$$;

-- Register known official SCERT entry points without asserting a specific edition
-- or pretending that individual chapters have already been verified against them.
insert into content_source(source_kind,title,provider,source_url,edition,language,status)
values
  ('SCERT_CATALOGUE','SCERT Bihar textbook catalogue','SCERT Bihar','https://scert.bihar.gov.in/textbooks','UNVERIFIED','hi','REFERENCE'),
  ('SCERT_TEACHER_HANDBOOK','Mathematics teacher handbook, Classes 6–8','SCERT Bihar','https://scert.bihar.gov.in/eresources/mathematics-handbook-for-teachers-1753723347','UNVERIFIED','hi','REFERENCE'),
  ('SCERT_TEACHER_HANDBOOK','Science teacher handbook, Classes 6–8','SCERT Bihar','https://scert.bihar.gov.in/eresources/science-handbook-for-teachers-class-6-8-1753723306','UNVERIFIED','hi','REFERENCE'),
  ('SCERT_TEXTBOOK','गणित भाग-6','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%97%E0%A4%A3%E0%A4%BF%E0%A4%A4-%E0%A4%AD%E0%A4%BE%E0%A4%97-6-1707973215','UNVERIFIED','hi','REFERENCE'),
  ('SCERT_TEXTBOOK','विज्ञान भाग-2, Class 7','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%B5%E0%A4%BF%E0%A4%9C%E0%A4%BE%E0%A4%A8-%E0%A4%AD%E0%A4%BE%E0%A4%97-2-1708062711','UNVERIFIED','hi','REFERENCE'),
  ('SCERT_TEXTBOOK','गणित भाग-8','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%97%E0%A4%A3%E0%A4%BF%E0%A4%A4-%E0%A4%AD%E0%A4%BE%E0%A4%97-8-1708403831','UNVERIFIED','hi','REFERENCE')
on conflict(source_kind,title,edition) do update set
  provider=excluded.provider,source_url=excluded.source_url,language=excluded.language,status='REFERENCE';

-- Audit requirements are contracts, not claims that the chapters already satisfy them.
insert into lesson_requirement(chapter_id,requirement_code,description,min_count,required)
select ch.id,r.code,r.description,r.min_count,r.required
from curriculum_chapter ch
cross join (values
  ('PREREQUISITE','A prerequisite or prior-knowledge bridge is present.',1,true),
  ('EXPLANATION','An original, clear teaching explanation is present.',1,true),
  ('WORKED_EXAMPLE','At least one worked example is present.',1,true),
  ('GUIDED_PRACTICE','At least one guided practice activity is present.',1,true),
  ('INDEPENDENT_PRACTICE','At least one independent practice activity is present.',1,true),
  ('RECAP','A concise recap or summary is present.',1,true),
  ('VISUAL_OR_NOT_REQUIRED','A useful visual is present, or a reviewer records why it is not needed.',0,false),
  ('NCERT_OR_TEXTBOOK_MAPPING','The chapter has a verified textbook/source mapping.',1,true),
  ('BOARD_FORMAT_COVERAGE','At least one board-style assessment format is present.',1,true),
  ('SOURCE_TAGGED_QUESTIONS','Source provenance is recorded when third-party questions are used.',1,true)
) as r(code,description,min_count,required)
where ch.active=true and ch.content_status='PUBLISHED'
on conflict(chapter_id,requirement_code) do update set
  description=excluded.description,min_count=excluded.min_count,required=excluded.required;

-- These are generic lesson shells, not completed lessons. Keep them editable in
-- admin, but unpublished until real, reviewed teaching blocks and assessments exist.
update lesson
set status='DRAFT'
where active=true and code ~ '-(foundation|guided-practice|mastery)$';

update question q
set active=false,review_status='REJECTED',
    review_notes='Generated template question disabled; replace with reviewed, original practice.'
where q.active=true
  and q.lesson_id in (
    select l.id from lesson l
    where l.code ~ '-(foundation|guided-practice|mastery)$'
  );

-- These two additional Class 7 Science entries were previously labelled as official
-- chapter records without verified source evidence. Keep them archived pending review.
update curriculum_chapter ch
set active=false,content_status='ARCHIVED'
from curriculum_subject s join curriculum_class c on c.id=s.class_id
where ch.subject_id=s.id and c.code='7' and s.code='science'
  and ch.code in ('appendix','human-body');

-- Preserve the original algebra questions after checking their arithmetic and
-- explanations; provenance remains author-created, not textbook-derived.
update question
set review_status='APPROVED',
    review_notes='Mathematical answer and explanation checked; original QuantaEdge practice.',
    reviewed_at=coalesce(reviewed_at,now())
where prompt in (
  'x + 4 = 9 में x की value क्या होगी?',
  'Variable की value हमेशा 0 होती है।'
);

-- Give the existing simple-equations lesson original teaching blocks so it is not
-- an empty published shell.
insert into lesson_block(lesson_id,sequence_no,block_type,content)
select l.id,1,'EXPLANATION',jsonb_build_object(
  'heading','समीकरण को संतुलित रखना',
  'body','समीकरण में बराबर के दोनों पक्ष समान मान दिखाते हैं। अज्ञात संख्या निकालने के लिए दोनों पक्षों पर एक ही संक्रिया करें।',
  'workedExample',jsonb_build_object('equation','x + 5 = 12','step1','दोनों पक्षों से 5 घटाएँ।','step2','x = 12 − 5 = 7','check','7 + 5 = 12')
)
from lesson l join curriculum_chapter ch on ch.id=l.chapter_id
join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
where c.code='7' and s.code='maths' and l.code='simple-equations'
  and not exists(select 1 from lesson_block b where b.lesson_id=l.id and b.sequence_no=1);

insert into lesson_block(lesson_id,sequence_no,block_type,content)
select l.id,2,'CHALLENGE',jsonb_build_object(
  'title','अब स्वयं हल करें',
  'prompt','x − 5 = 3 में x का मान निकालिए। अपने कदम लिखिए और उत्तर को मूल समीकरण में रखकर जाँचिए।',
  'hint','x को अकेला करने के लिए दोनों पक्षों में 5 जोड़ें।'
)
from lesson l join curriculum_chapter ch on ch.id=l.chapter_id
join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
where c.code='7' and s.code='maths' and l.code='simple-equations'
  and not exists(select 1 from lesson_block b where b.lesson_id=l.id and b.sequence_no=2);

insert into lesson_block(lesson_id,sequence_no,block_type,content)
select l.id,3,'SUMMARY',jsonb_build_object(
  'points',jsonb_build_array(
    'दोनों पक्षों पर एक ही संक्रिया करने से समीकरण संतुलित रहता है।',
    'जोड़ का उलटा घटाव और घटाव का उलटा जोड़ है।',
    'हल को मूल समीकरण में रखकर जाँचें।'
  )
)
from lesson l join curriculum_chapter ch on ch.id=l.chapter_id
join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
where c.code='7' and s.code='maths' and l.code='simple-equations'
  and not exists(select 1 from lesson_block b where b.lesson_id=l.id and b.sequence_no=3);

with target as (
  select l.id as lesson_id,l.objective_id
  from lesson l join curriculum_chapter ch on ch.id=l.chapter_id
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and l.code='simple-equations'
), seeds(prompt,explanation,difficulty,sort_order,answer_key) as (
  values
    ('2x = 12 में x का मान क्या है?','दोनों पक्षों को 2 से भाग देने पर x = 6 मिलता है।','CORE',1,'B'),
    ('x − 5 = 3 में x का मान क्या है?','दोनों पक्षों में 5 जोड़ने पर x = 8 मिलता है।','CORE',2,'B')
), inserted as (
  insert into question(
    lesson_id,objective_id,question_type,prompt,explanation,difficulty,sort_order,
    source_kind,source_title,source_ref,board,tags,marks,exam_format,topic,subtopic,skill,
    answer_payload,review_status,review_notes,reviewed_at
  )
  select target.lesson_id,target.objective_id,'MCQ',seeds.prompt,seeds.explanation,seeds.difficulty,seeds.sort_order,
    'AUTHOR_CREATED','QuantaEdge original practice','author-created:class7-maths-simple-equations',null,
    jsonb_build_array('author-created','original-practice','class-7','maths'),1,'MCQ',
    'Simple equations','One-step equations','Solve and verify',
    jsonb_build_object('kind','OPTION','value',seeds.answer_key),'APPROVED',
    'Mathematical answer, distractors and explanation checked; original practice.',now()
  from target cross join seeds
  where not exists(select 1 from question q where q.prompt=seeds.prompt)
  returning id,prompt
)
insert into question_option(question_id,option_key,label,is_correct,sort_order)
select inserted.id,o.option_key,o.label,o.is_correct,o.sort_order
from inserted
join (values
  ('2x = 12 में x का मान क्या है?','A','4',false,1),
  ('2x = 12 में x का मान क्या है?','B','6',true,2),
  ('2x = 12 में x का मान क्या है?','C','10',false,3),
  ('2x = 12 में x का मान क्या है?','D','24',false,4),
  ('x − 5 = 3 में x का मान क्या है?','A','2',false,1),
  ('x − 5 = 3 में x का मान क्या है?','B','8',true,2),
  ('x − 5 = 3 में x का मान क्या है?','C','−2',false,3),
  ('x − 5 = 3 में x का मान क्या है?','D','15',false,4)
) as o(prompt,option_key,label,is_correct,sort_order) on o.prompt=inserted.prompt;

update question q
set answer_payload=jsonb_build_object(
  'kind','OPTION',
  'value',(select qo.option_key from question_option qo where qo.question_id=q.id and qo.is_correct order by qo.sort_order limit 1)
)
where q.question_type in ('MCQ','TRUE_FALSE')
  and q.answer_payload='{}'::jsonb
  and exists(select 1 from question_option qo where qo.question_id=q.id and qo.is_correct);

insert into app_metadata(key,value)
values ('schema','curriculum-source-review-and-real-content-v14')
on conflict(key) do update set value=excluded.value;
