-- V15: production identity, OTP challenges, sessions and guardian/child consent.
create table user_account (
  id bigint generated by default as identity primary key,
  public_id uuid not null unique,
  mobile_e164 varchar(20) not null unique,
  display_name varchar(120),
  role varchar(30) not null default 'PARENT',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (role in ('PARENT','ADMIN'))
);

create table otp_challenge (
  id bigint generated by default as identity primary key,
  mobile_e164 varchar(20) not null,
  purpose varchar(30) not null,
  code_hash varchar(128) not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  consumed_at timestamptz,
  requested_at timestamptz not null default now(),
  check (purpose in ('LOGIN','SIGNUP')),
  check (attempts between 0 and 10)
);

create table auth_session (
  id bigint generated by default as identity primary key,
  token_hash varchar(128) not null unique,
  user_id bigint references user_account(id) on delete cascade,
  student_id bigint references student(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  check (user_id is not null or student_id is not null)
);

create table guardian_student (
  id bigint generated by default as identity primary key,
  guardian_user_id bigint not null references user_account(id) on delete cascade,
  student_id bigint not null references student(id) on delete cascade,
  relationship varchar(40) not null default 'PARENT',
  consent_status varchar(30) not null default 'CONSENTED',
  consented_at timestamptz not null default now(),
  active boolean not null default true,
  unique(guardian_user_id,student_id),
  check(consent_status in ('PENDING','CONSENTED','REVOKED'))
);

alter table student
  add column if not exists access_pin_hash varchar(128),
  add column if not exists access_pin_set_at timestamptz;

create index idx_otp_mobile_requested on otp_challenge(mobile_e164,requested_at);
create index idx_auth_session_token on auth_session(token_hash,expires_at,revoked_at);
create index idx_guardian_student_guardian on guardian_student(guardian_user_id,active);
create index idx_guardian_student_student on guardian_student(student_id,active);

insert into app_metadata(key,value) values ('schema','auth-and-guardians-v15')
on conflict(key) do update set value=excluded.value;
