-- V16: persisted answer state, concept mastery and content assets.
alter table student_question_attempt
  alter column selected_option drop not null;

alter table student_question_attempt
  add column if not exists answer_text text;

alter table question
  add column if not exists concept_id bigint references chapter_concept(id);

update question q
set concept_id = (
  select cc.id
  from chapter_concept cc
  where cc.chapter_id=(select chapter_id from lesson where id=q.lesson_id)
  order by cc.concept_order,cc.id
  limit 1
)
where q.concept_id is null;

create table student_concept_mastery (
  id bigint generated by default as identity primary key,
  student_id bigint not null references student(id) on delete cascade,
  concept_id bigint not null references chapter_concept(id) on delete cascade,
  mastery_percent integer not null default 0,
  attempts integer not null default 0,
  graded_attempts integer not null default 0,
  correct_attempts integer not null default 0,
  last_attempt_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(student_id,concept_id),
  check(mastery_percent between 0 and 100),
  check(attempts >= 0),
  check(graded_attempts >= 0),
  check(correct_attempts >= 0)
);

create table content_asset (
  id bigint generated by default as identity primary key,
  asset_type varchar(30) not null,
  title varchar(240) not null,
  alt_text varchar(500),
  url varchar(1200) not null,
  source_kind varchar(40) not null default 'AUTHOR_CREATED',
  source_title varchar(300),
  source_ref varchar(300),
  license_note varchar(500),
  status varchar(30) not null default 'DRAFT',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(asset_type in ('IMAGE','DIAGRAM','VIDEO','AUDIO')),
  check(status in ('DRAFT','REVIEW','PUBLISHED','ARCHIVED'))
);

alter table lesson_block
  add column if not exists asset_id bigint references content_asset(id) on delete set null;

create index idx_mastery_student on student_concept_mastery(student_id,mastery_percent,updated_at);
create index idx_question_concept on question(concept_id);
create index idx_asset_status on content_asset(status,asset_type);

insert into app_metadata(key,value) values ('schema','learning-state-v16')
on conflict(key) do update set value=excluded.value;
