-- V17: content governance and admin audit trail.
alter table question add column if not exists review_status varchar(30) not null default 'DRAFT';
alter table question drop constraint if exists question_review_status_check;
alter table question add constraint question_review_status_check
  check(review_status in ('DRAFT','REVIEW','APPROVED','PUBLISHED','REJECTED'));
update question set review_status='PUBLISHED' where active=true and review_status='DRAFT';

create table admin_action_log (
  id bigint generated by default as identity primary key,
  admin_user_id bigint not null references user_account(id) on delete restrict,
  action varchar(80) not null,
  resource varchar(120),
  detail text,
  created_at timestamptz not null default now()
);

create index idx_admin_action_log_admin_created on admin_action_log(admin_user_id,created_at desc);

insert into app_metadata(key,value) values ('schema','content-governance-v17')
on conflict(key) do update set value=excluded.value;
