create table app_metadata (
  id bigint generated by default as identity primary key,
  key varchar(100) not null unique,
  value varchar(500) not null,
  created_at timestamptz not null default now()
);

insert into app_metadata(key, value) values ('schema', 'foundation-v1');
