-- V21: persisted, auditable AI tutor sessions and messages.
create table tutor_session (
  id bigint generated by default as identity primary key,
  public_id uuid not null unique,
  student_id bigint not null references student(id) on delete cascade,
  lesson_id bigint not null references lesson(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_message_at timestamptz,
  ended_at timestamptz
);

create table tutor_message (
  id bigint generated by default as identity primary key,
  session_id bigint not null references tutor_session(id) on delete cascade,
  role varchar(20) not null,
  mode varchar(30),
  message text not null,
  model varchar(120),
  provider_response_id varchar(160),
  input_tokens integer,
  output_tokens integer,
  created_at timestamptz not null default now(),
  check(role in ('USER','ASSISTANT')),
  check(mode is null or mode in ('HINT','EXPLAIN','EXAMPLE','STEP_BY_STEP','CHECK_MY_WORK'))
);

create index idx_tutor_session_student_lesson on tutor_session(student_id,lesson_id,created_at desc);
create index idx_tutor_message_session on tutor_message(session_id,created_at);
create index idx_tutor_message_created on tutor_message(created_at);

insert into app_metadata(key,value) values ('schema','ai-tutor-v21')
on conflict(key) do update set value=excluded.value;
