-- V26: align the schema with the market-ready features without seeding generic questions as real content.
-- Source entries are candidate references only. Chapter/page coverage stays NEEDS_REVIEW
-- until an editor checks the exact downloaded edition and printed/PDF page references.

alter table chapter_source
  add column if not exists source_chapter_title varchar(300),
  add column if not exists source_locator varchar(300),
  add column if not exists coverage_type varchar(40) not null default 'CURRICULUM_CANDIDATE';

alter table chapter_source
  drop constraint if exists chapter_source_chapter_id_source_id_key;
create unique index if not exists uq_chapter_source_coverage_type
  on chapter_source(chapter_id,source_id,coverage_type);

alter table chapter_concept
  add column if not exists prerequisite_codes jsonb not null default '[]'::jsonb,
  add column if not exists source_refs jsonb not null default '[]'::jsonb;

alter table question
  drop constraint if exists question_question_type_check;
alter table question
  add constraint question_question_type_check check (question_type in (
    'MCQ','TRUE_FALSE','INPUT','MATCH','ORDER','ASSERTION_REASON',
    'CASE_BASED','SHORT_ANSWER','LONG_ANSWER','NUMERICAL','DIAGRAM','MAP','SOURCE_BASED'
  ));

alter table lesson_block
  drop constraint if exists lesson_block_block_type_check;
alter table lesson_block
  add constraint lesson_block_block_type_check check (block_type in (
    'EXPLANATION','IMAGE','DIAGRAM','VIDEO','QUESTION','MCQ','TRUE_FALSE','MATCH','ORDER',
    'INPUT','HINT','AI_HELP','SUMMARY','CHALLENGE','PREREQUISITE','WORKED_EXAMPLE',
    'GUIDED_PRACTICE','INDEPENDENT_PRACTICE','RECAP'
  ));

create table if not exists question_source_tag (
  id bigint generated by default as identity primary key,
  question_id bigint not null references question(id) on delete cascade,
  tag varchar(100) not null,
  unique(question_id,tag)
);

-- Minimum editorial coverage targets, not pre-created questions. Optional formats
-- remain explicitly optional until the chapter editor records that the format fits.
create table if not exists chapter_assessment_requirement (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references curriculum_chapter(id) on delete cascade,
  question_type varchar(40) not null,
  minimum_count integer not null default 1,
  required boolean not null default true,
  rationale varchar(500) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(chapter_id,question_type),
  check(minimum_count >= 0),
  check(question_type in (
    'MCQ','TRUE_FALSE','INPUT','MATCH','ORDER','ASSERTION_REASON','CASE_BASED',
    'SHORT_ANSWER','LONG_ANSWER','NUMERICAL','DIAGRAM','MAP','SOURCE_BASED'
  ))
);

insert into content_source(source_kind,title,provider,source_url,edition,language,status)
values
 ('STATE_TEXTBOOK','Bihar SCERT Class 6 Mathematics — गणित भाग-6','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%97%E0%A4%A3%E0%A4%BF%E0%A4%A4-%E0%A4%AD%E0%A4%BE%E0%A4%97-6-1707973215','UNVERIFIED','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 7 Mathematics — गणित भाग-7','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%97%E0%A4%A3%E0%A4%BF%E0%A4%A4-%E0%A4%AD%E0%A4%BE%E0%A4%97-7-1708060463','UNVERIFIED','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 8 Mathematics — गणित भाग-8','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%97%E0%A4%A3%E0%A4%BF%E0%A4%A4-%E0%A4%AD%E0%A4%BE%E0%A4%97-8-1708403831','UNVERIFIED','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 6 Science — विज्ञान भाग-1','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%B5%E0%A4%BF%E0%A4%9C%E0%A5%8D%E0%A4%9E%E0%A4%BE%E0%A4%A8-%E0%A4%AD%E0%A4%BE%E0%A4%97-1-1707973674','UNVERIFIED','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 7 Science — विज्ञान भाग-2','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%B5%E0%A4%BF%E0%A4%9C%E0%A5%8D%E0%A4%9E%E0%A4%BE%E0%A4%A8-%E0%A4%AD%E0%A4%BE%E0%A4%97-2-1708062711','UNVERIFIED','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 8 Science — विज्ञान भाग-3','SCERT Bihar','https://scert.bihar.gov.in/eresources/%E0%A4%B5%E0%A4%BF%E0%A4%9C%E0%A5%8D%E0%A4%9E%E0%A4%BE%E0%A4%A8-%E0%A4%AD%E0%A4%BE%E0%A4%97-3-1708404249','UNVERIFIED','hi','REFERENCE')
on conflict(source_kind,title,edition) do update set
  provider=excluded.provider,source_url=excluded.source_url,language=excluded.language,status='REFERENCE';

-- Candidate book associations are stored, but never marked MAPPED/COVERED by automation.
insert into chapter_source(
  chapter_id,source_id,source_chapter_no,source_chapter_title,source_locator,coverage_type,coverage_status,notes
)
select ch.id,src.id,null,null,null,'CURRICULUM_CANDIDATE','NEEDS_REVIEW',
  'Candidate book selected by class and subject only. Verify the actual downloaded edition, chapter title and page range before marking MAPPED.'
from curriculum_chapter ch
join curriculum_subject s on s.id=ch.subject_id
join curriculum_class c on c.id=s.class_id
join content_source src on src.source_kind='STATE_TEXTBOOK'
 and src.edition='UNVERIFIED'
 and (
   (c.code='6' and s.code='maths' and src.title like 'Bihar SCERT Class 6 Mathematics%') or
   (c.code='7' and s.code='maths' and src.title like 'Bihar SCERT Class 7 Mathematics%') or
   (c.code='8' and s.code='maths' and src.title like 'Bihar SCERT Class 8 Mathematics%') or
   (c.code='6' and s.code='science' and src.title like 'Bihar SCERT Class 6 Science%') or
   (c.code='7' and s.code='science' and src.title like 'Bihar SCERT Class 7 Science%') or
   (c.code='8' and s.code='science' and src.title like 'Bihar SCERT Class 8 Science%')
 )
where c.code in ('6','7','8') and s.code in ('maths','science')
  and ch.active=true and ch.content_status='PUBLISHED'
on conflict(chapter_id,source_id,coverage_type) do update set
  coverage_status='NEEDS_REVIEW',
  notes='Candidate book selected by class and subject only. Verify exact edition, chapter title and page range.';

-- Add a conservative question-type plan per active chapter. These are targets, not
-- question rows. The admin inventory reports actual created/reviewed questions separately.
insert into chapter_assessment_requirement(chapter_id,question_type,minimum_count,required,rationale)
select ch.id, r.question_type, r.minimum_count,
  case
    when r.question_type in ('MCQ','TRUE_FALSE','INPUT','MATCH','ORDER','CASE_BASED','SHORT_ANSWER','LONG_ANSWER') then true
    when r.question_type='ASSERTION_REASON' then s.code='science'
    when r.question_type='NUMERICAL' then s.code='maths'
    when r.question_type='DIAGRAM' then (
      s.code='science' or ch.code in (
        'geometry-basics','elementary-shapes','data-handling','symmetry','practical-geometry',
        'lines-angles','triangles','congruence','perimeter-area','solid-shapes','quadrilaterals',
        'squares-roots','cubes-roots','mensuration','algebraic-identities','graphs','factorisation'
      )
    )
    else false
  end,
  r.rationale
from curriculum_chapter ch
join curriculum_subject s on s.id=ch.subject_id
join curriculum_class c on c.id=s.class_id
cross join (values
  ('MCQ',1,'Core multiple-choice check using this chapter’s real concept.'),
  ('TRUE_FALSE',1,'Use only a statement that can be unambiguously justified.'),
  ('INPUT',1,'Short answer/input response; add a verified answer key or rubric.'),
  ('MATCH',1,'Use only when the chapter has meaningful pairs to match.'),
  ('ORDER',1,'Use only when the concept has a meaningful sequence or process.'),
  ('ASSERTION_REASON',1,'Causal-reasoning item; required for Science.'),
  ('CASE_BASED',1,'An original age-appropriate context tied to the actual chapter concept.'),
  ('SHORT_ANSWER',1,'Original short response assessed against a rubric.'),
  ('LONG_ANSWER',1,'Original structured response assessed against a rubric.'),
  ('NUMERICAL',1,'Numerical problem; required for Mathematics.'),
  ('DIAGRAM',1,'Diagram/label task only where the chapter benefits from a visual representation.'),
  ('MAP',1,'Optional; only create where spatial/map context genuinely fits.'),
  ('SOURCE_BASED',1,'Optional until the exact source/edition and rights are reviewed.')
) as r(question_type,minimum_count,rationale)
where c.code in ('6','7','8') and s.code in ('maths','science')
  and ch.active=true and ch.content_status='PUBLISHED'
on conflict(chapter_id,question_type) do update set
  minimum_count=excluded.minimum_count,required=excluded.required,rationale=excluded.rationale;

-- Correct two legacy Class 7 Mathematics chapter placements before archiving duplicates.
-- Their authored questions/teaching blocks move with the lesson; no learning records are created.
with target as (
  select ch.id as chapter_id
  from curriculum_chapter ch
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and ch.code='algebraic-expressions' and ch.active=true
), old_chapter as (
  select ch.id as chapter_id
  from curriculum_chapter ch
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and ch.code='algebra' and ch.active=true
)
update learning_objective o
set chapter_id=(select chapter_id from target)
where o.chapter_id=(select chapter_id from old_chapter)
  and o.code='identify-variable'
  and not exists(select 1 from learning_objective t where t.chapter_id=(select chapter_id from target) and t.code=o.code);

with target as (
  select ch.id as chapter_id
  from curriculum_chapter ch
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and ch.code='simple-equations' and ch.active=true
), old_chapter as (
  select ch.id as chapter_id
  from curriculum_chapter ch
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and ch.code='algebra' and ch.active=true
)
update learning_objective o
set chapter_id=(select chapter_id from target)
where o.chapter_id=(select chapter_id from old_chapter)
  and o.code='solve-simple-equation'
  and not exists(select 1 from learning_objective t where t.chapter_id=(select chapter_id from target) and t.code=o.code);

with target as (
  select ch.id as chapter_id
  from curriculum_chapter ch
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and ch.code='algebraic-expressions' and ch.active=true
), old_chapter as (
  select ch.id as chapter_id
  from curriculum_chapter ch
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and ch.code='algebra' and ch.active=true
)
update lesson l
set chapter_id=(select chapter_id from target)
where l.chapter_id=(select chapter_id from old_chapter) and l.code='variable-basics'
  and not exists(select 1 from lesson t where t.chapter_id=(select chapter_id from target) and t.code=l.code);

with target as (
  select ch.id as chapter_id
  from curriculum_chapter ch
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and ch.code='simple-equations' and ch.active=true
), old_chapter as (
  select ch.id as chapter_id
  from curriculum_chapter ch
  join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
  where c.code='7' and s.code='maths' and ch.code='algebra' and ch.active=true
)
update lesson l
set chapter_id=(select chapter_id from target)
where l.chapter_id=(select chapter_id from old_chapter) and l.code='simple-equations'
  and not exists(select 1 from lesson t where t.chapter_id=(select chapter_id from target) and t.code=l.code);

update curriculum_chapter ch
set active=false,content_status='ARCHIVED'
from curriculum_subject s join curriculum_class c on c.id=s.class_id
where ch.subject_id=s.id and c.code='7' and s.code='maths'
  and ch.code in ('algebra','fractions');

-- Store candidate source metadata in the CMS, without claiming verified coverage.
update curriculum_chapter ch
set curriculum_source=src.title,curriculum_source_url=src.source_url,
    curriculum_source_edition=src.edition,curriculum_source_verified=false,
    curriculum_source_pages=null
from curriculum_subject s join curriculum_class c on c.id=s.class_id
join content_source src on src.source_kind='STATE_TEXTBOOK' and src.edition='UNVERIFIED'
 and (
   (c.code='6' and s.code='maths' and src.title like 'Bihar SCERT Class 6 Mathematics%') or
   (c.code='7' and s.code='maths' and src.title like 'Bihar SCERT Class 7 Mathematics%') or
   (c.code='8' and s.code='maths' and src.title like 'Bihar SCERT Class 8 Mathematics%') or
   (c.code='6' and s.code='science' and src.title like 'Bihar SCERT Class 6 Science%') or
   (c.code='7' and s.code='science' and src.title like 'Bihar SCERT Class 7 Science%') or
   (c.code='8' and s.code='science' and src.title like 'Bihar SCERT Class 8 Science%')
 )
where ch.subject_id=s.id and ch.active=true and ch.content_status='PUBLISHED';

update lesson l
set alignment_source_title=src.title,alignment_source_url=src.source_url,
    alignment_source_edition=src.edition,alignment_source_verified=false,alignment_page_range=null
from curriculum_chapter ch
join curriculum_subject s on s.id=ch.subject_id join curriculum_class c on c.id=s.class_id
join content_source src on src.source_kind='STATE_TEXTBOOK' and src.edition='UNVERIFIED'
 and (
   (c.code='6' and s.code='maths' and src.title like 'Bihar SCERT Class 6 Mathematics%') or
   (c.code='7' and s.code='maths' and src.title like 'Bihar SCERT Class 7 Mathematics%') or
   (c.code='8' and s.code='maths' and src.title like 'Bihar SCERT Class 8 Mathematics%') or
   (c.code='6' and s.code='science' and src.title like 'Bihar SCERT Class 6 Science%') or
   (c.code='7' and s.code='science' and src.title like 'Bihar SCERT Class 7 Science%') or
   (c.code='8' and s.code='science' and src.title like 'Bihar SCERT Class 8 Science%')
 )
where l.chapter_id=ch.id and l.active=true;

-- Ensure generated chapter shells have canonical stage codes but remain drafts.
update lesson
set code=regexp_replace(code,'-guided-practice$','-guided')
where active=true and status='DRAFT' and code like '%-guided-practice'
  and not exists(select 1 from lesson l2 where l2.chapter_id=lesson.chapter_id
    and l2.code=regexp_replace(lesson.code,'-guided-practice$','-guided'));

insert into app_metadata(key,value)
values ('schema','market-ready-content-governance-v26')
on conflict(key) do update set value=excluded.value;
