-- V28: explicit, auditable subscriptions to subject tracks per student.
create table student_track_enrollment (
  id bigint generated by default as identity primary key,
  student_id bigint not null references student(id) on delete cascade,
  subject_id bigint not null references curriculum_subject(id),
  status varchar(20) not null default 'ACTIVE',
  subscribed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, subject_id),
  check(status in ('ACTIVE','PAUSED','ENDED'))
);

create index idx_student_track_active on student_track_enrollment(student_id, status, subject_id);

-- Preserve existing access by enrolling current profiles in active subjects for their class.
insert into student_track_enrollment(student_id, subject_id, status)
select st.id, s.id, 'ACTIVE'
from student st
join curriculum_class c on c.code=st.class_code and c.active=true
join curriculum_subject s on s.class_id=c.id and s.active=true
on conflict(student_id, subject_id) do nothing;

insert into app_metadata(key,value)
values ('schema','student-track-enrollment-v28')
on conflict(key) do update set value=excluded.value;
