create table curriculum_class (
  id bigint generated by default as identity primary key,
  code varchar(30) not null unique,
  display_name varchar(100) not null,
  board varchar(80) not null,
  sort_order integer not null default 0,
  active boolean not null default true
);

create table curriculum_subject (
  id bigint generated by default as identity primary key,
  class_id bigint not null references curriculum_class(id),
  code varchar(40) not null,
  display_name varchar(100) not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  unique(class_id, code)
);

create table curriculum_chapter (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references curriculum_subject(id),
  code varchar(60) not null,
  display_name varchar(160) not null,
  description varchar(500),
  sort_order integer not null default 0,
  active boolean not null default true,
  unique(subject_id, code)
);

insert into curriculum_class(code, display_name, board, sort_order) values
('6','Class 6','Bihar Board',1),
('7','Class 7','Bihar Board',2),
('8','Class 8','Bihar Board',3);

insert into curriculum_subject(class_id, code, display_name, sort_order)
select id, 'maths', 'गणित', 1 from curriculum_class where code in ('6','7','8');

insert into curriculum_subject(class_id, code, display_name, sort_order)
select id, 'science', 'विज्ञान', 2 from curriculum_class where code in ('6','7','8');

insert into curriculum_chapter(subject_id, code, display_name, description, sort_order)
select s.id, 'fractions', 'भिन्न', 'भिन्नों को समझना, तुलना करना और गणना करना।', 1
from curriculum_subject s join curriculum_class c on c.id=s.class_id
where s.code='maths' and c.code='7';

insert into curriculum_chapter(subject_id, code, display_name, description, sort_order)
select s.id, 'algebra', 'बीजगणित', 'Variables, expressions और सरल equations की शुरुआत।', 2
from curriculum_subject s join curriculum_class c on c.id=s.class_id
where s.code='maths' and c.code='7';

insert into curriculum_chapter(subject_id, code, display_name, description, sort_order)
select s.id, 'force-pressure', 'बल तथा दाब', 'बल, दाब और उनके दैनिक जीवन में उपयोग।', 1
from curriculum_subject s join curriculum_class c on c.id=s.class_id
where s.code='science' and c.code='8';

insert into app_metadata(key, value) values ('schema', 'curriculum-v2')
on conflict (key) do update set value=excluded.value;