-- V31: separate staff identities from parent/student accounts and add task permissions + audit trail.
-- Existing admin identities are copied into the dedicated staff table before their user_account role is normalized.
create table staff_account (
  id bigint generated by default as identity primary key,
  public_id uuid not null unique,
  mobile_e164 varchar(24) not null unique,
  display_name varchar(120) not null,
  role varchar(32) not null check (role in ('ADMIN','MANAGER','MODERATOR','CONTENT_AUTHOR','CONTENT_REVIEWER','PUBLISHER')),
  active boolean not null default true,
  created_by_staff_id bigint references staff_account(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

alter table auth_session
  add column if not exists staff_id bigint references staff_account(id) on delete cascade;

create index if not exists idx_auth_session_staff_active
  on auth_session(staff_id, expires_at)
  where staff_id is not null;

-- Permit an authenticated session to belong to a staff identity as well as a parent/user or student.
-- Replace only a legacy guard that required user_id or student_id; keep unrelated constraints intact.
do $staff_auth_session_constraint$ declare
  constraint_row record;
  definition text;
begin
  for constraint_row in
    select conname, pg_get_constraintdef(oid) as definition
    from pg_constraint
    where conrelid='public.auth_session'::regclass and contype='c'
  loop
    definition := constraint_row.definition;
    if definition ilike '%user_id IS NOT NULL%'
       and definition ilike '%student_id IS NOT NULL%'
       and definition ilike '% OR %' then
      execute format('alter table public.auth_session drop constraint %I', constraint_row.conname);
    end if;
  end loop;
end $staff_auth_session_constraint$;

do $staff_auth_session_identity$ begin
  if not exists (
    select 1 from pg_constraint
    where conrelid='public.auth_session'::regclass
      and conname='auth_session_identity_required'
  ) then
    alter table public.auth_session
      add constraint auth_session_identity_required
      check (user_id is not null or student_id is not null or staff_id is not null);
  end if;
end $staff_auth_session_identity$;

create table staff_permission_catalog (
  permission_key varchar(64) primary key,
  display_name varchar(120) not null,
  description varchar(300) not null,
  created_at timestamptz not null default now()
);

insert into staff_permission_catalog(permission_key, display_name, description) values
 ('CONTENT_VIEW','View learning content','Open the curriculum and inspect chapters, topics and lesson content.'),
 ('CONTENT_CREATE','Create content','Create new chapters and micro-topics as drafts.'),
 ('CONTENT_EDIT','Edit content','Change lesson details, teaching blocks and practice questions.'),
 ('CONTENT_SUBMIT','Submit for review','Send authored content to the review queue.'),
 ('CONTENT_REVIEW','Review content','Review content and approve or return practice questions.'),
 ('CONTENT_PUBLISH','Publish content','Publish or unpublish approved content after all checks pass.'),
 ('STAFF_MANAGE','Manage staff','Create staff accounts, grant permissions and suspend staff access.'),
 ('AUDIT_VIEW','View audit trail','Inspect staff access and activity records.'),
 ('USER_MANAGE','Manage accounts','Manage parent and student accounts.')
on conflict(permission_key) do update
set display_name=excluded.display_name, description=excluded.description;

create table staff_permission_grant (
  staff_id bigint not null references staff_account(id) on delete cascade,
  permission_key varchar(64) not null references staff_permission_catalog(permission_key),
  granted_by_staff_id bigint references staff_account(id) on delete set null,
  granted_at timestamptz not null default now(),
  primary key(staff_id, permission_key)
);

-- Preserve currently configured administrators as staff identities. Parent profiles remain user_account rows.
insert into staff_account(public_id, mobile_e164, display_name, role, active, created_at, updated_at)
select public_id, mobile_e164, coalesce(nullif(trim(display_name),''),'Administrator'), 'ADMIN', active, created_at, updated_at
from user_account
where role='ADMIN'
on conflict(mobile_e164) do nothing;

insert into staff_permission_grant(staff_id, permission_key)
select s.id, p.permission_key
from staff_account s
cross join staff_permission_catalog p
where s.role='ADMIN'
on conflict(staff_id, permission_key) do nothing;

-- Revoke sessions that were issued while an admin identity still used the user_account role.
-- Staff must establish a fresh session from the dedicated staff identity before using the console.
update auth_session s
set revoked_at=now()
where s.revoked_at is null
  and s.user_id in (
    select u.id
    from user_account u
    join staff_account staff on staff.mobile_e164=u.mobile_e164
    where u.role='ADMIN'
  );

-- An administrator identity is no longer also a parent/user role. Its original row is retained
-- for referential integrity and any guardian relations; normal parent authentication won't use it
-- for staff sign-in, which has the dedicated STAFF_LOGIN purpose.
update user_account set role='PARENT', updated_at=now() where role='ADMIN';

create table staff_audit_log (
  id bigint generated by default as identity primary key,
  actor_staff_id bigint references staff_account(id) on delete set null,
  actor_role varchar(32) not null,
  http_method varchar(12) not null,
  request_path varchar(500) not null,
  response_status integer not null,
  remote_address varchar(80),
  user_agent varchar(500),
  created_at timestamptz not null default now()
);

create index idx_staff_audit_created on staff_audit_log(created_at desc);
create index idx_staff_audit_actor_created on staff_audit_log(actor_staff_id, created_at desc);

-- Make the reviewer visible on the question itself as well as in the append-only staff activity trail.
alter table question
  add column if not exists reviewed_by_staff_id bigint references staff_account(id) on delete set null;

create index if not exists idx_question_reviewed_by_staff
  on question(reviewed_by_staff_id, reviewed_at desc)
  where reviewed_by_staff_id is not null;
