-- Password-based parent sign-in and per-parent student credentials.
alter table user_account add column if not exists password_hash varchar(100);

create table if not exists student_login_credential (
  id bigint generated by default as identity primary key,
  guardian_user_id bigint not null references user_account(id),
  student_id bigint not null references student(id),
  username varchar(32) not null,
  password_hash varchar(100) not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(guardian_user_id, student_id)
);

create unique index if not exists uq_student_login_credential_username
  on student_login_credential(guardian_user_id, lower(username))
  where active=true;

insert into app_metadata(key,value) values ('schema','password-auth-student-credentials-v37')
on conflict (key) do update set value=excluded.value;
