create table learning_objective (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references curriculum_chapter(id),
  code varchar(80) not null,
  title varchar(200) not null,
  description varchar(600),
  sort_order integer not null default 0,
  active boolean not null default true,
  unique(chapter_id, code)
);

create table lesson (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references curriculum_chapter(id),
  objective_id bigint references learning_objective(id),
  code varchar(100) not null,
  title varchar(240) not null,
  summary varchar(800),
  estimated_minutes integer not null default 10,
  status varchar(30) not null default 'DRAFT',
  sort_order integer not null default 0,
  active boolean not null default true,
  unique(chapter_id, code),
  check (estimated_minutes between 1 and 120),
  check (status in ('DRAFT','REVIEW','PUBLISHED','ARCHIVED'))
);

create table lesson_block (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references lesson(id) on delete cascade,
  sequence_no integer not null,
  block_type varchar(40) not null,
  content jsonb not null,
  active boolean not null default true,
  unique(lesson_id, sequence_no),
  check (block_type in (
    'EXPLANATION','IMAGE','DIAGRAM','VIDEO','QUESTION','MCQ','TRUE_FALSE',
    'MATCH','ORDER','INPUT','HINT','AI_HELP','SUMMARY','CHALLENGE'
  ))
);

create table question (
  id bigint generated by default as identity primary key,
  lesson_id bigint references lesson(id) on delete cascade,
  objective_id bigint references learning_objective(id),
  question_type varchar(30) not null,
  prompt varchar(1000) not null,
  explanation varchar(1200),
  difficulty varchar(20) not null default 'FOUNDATION',
  sort_order integer not null default 0,
  active boolean not null default true,
  check (question_type in ('MCQ','TRUE_FALSE','INPUT')),
  check (difficulty in ('FOUNDATION','CORE','CHALLENGE'))
);

create table question_option (
  id bigint generated by default as identity primary key,
  question_id bigint not null references question(id) on delete cascade,
  option_key varchar(20) not null,
  label varchar(500) not null,
  is_correct boolean not null default false,
  sort_order integer not null default 0,
  unique(question_id, option_key)
);

create index idx_objective_chapter on learning_objective(chapter_id, sort_order);
create index idx_lesson_chapter on lesson(chapter_id, sort_order);
create index idx_lesson_block_lesson on lesson_block(lesson_id, sequence_no);
create index idx_question_lesson on question(lesson_id, sort_order);
create index idx_question_option_question on question_option(question_id, sort_order);

insert into learning_objective(chapter_id, code, title, description, sort_order)
select ch.id, 'identify-variable', 'Variable को पहचानना',
       'Unknown value को variable के रूप में पहचानना और सरल उदाहरण समझना।', 1
from curriculum_chapter ch
join curriculum_subject s on s.id=ch.subject_id
join curriculum_class c on c.id=s.class_id
where c.code='7' and s.code='maths' and ch.code='algebra';

insert into learning_objective(chapter_id, code, title, description, sort_order)
select ch.id, 'solve-simple-equation', 'सरल equation हल करना',
       'एक-step equations को inverse operation की मदद से हल करना।', 2
from curriculum_chapter ch
join curriculum_subject s on s.id=ch.subject_id
join curriculum_class c on c.id=s.class_id
where c.code='7' and s.code='maths' and ch.code='algebra';

insert into lesson(chapter_id, objective_id, code, title, summary, estimated_minutes, status, sort_order)
select ch.id, o.id, 'variable-basics', 'Variable आखिर होता क्या है?',
       'Unknown value को समझें और x जैसे letters से numbers को represent करना सीखें।',
       12, 'PUBLISHED', 1
from curriculum_chapter ch
join curriculum_subject s on s.id=ch.subject_id
join curriculum_class c on c.id=s.class_id
join learning_objective o on o.chapter_id=ch.id and o.code='identify-variable'
where c.code='7' and s.code='maths' and ch.code='algebra';

insert into lesson(chapter_id, objective_id, code, title, summary, estimated_minutes, status, sort_order)
select ch.id, o.id, 'simple-equations', 'Simple equations को step-by-step हल करें',
       'Inverse operations का इस्तेमाल करके एक-step equations हल करना सीखें।',
       14, 'PUBLISHED', 2
from curriculum_chapter ch
join curriculum_subject s on s.id=ch.subject_id
join curriculum_class c on c.id=s.class_id
join learning_objective o on o.chapter_id=ch.id and o.code='solve-simple-equation'
where c.code='7' and s.code='maths' and ch.code='algebra';

insert into lesson_block(lesson_id, sequence_no, block_type, content)
select l.id, 1, 'EXPLANATION',
       '{"heading":"Variable क्या है?","body":"जब किसी संख्या की value हमें पता नहीं होती, तो हम उसे एक letter से दिखा सकते हैं। इसे variable कहते हैं।","language":"hi"}'::jsonb
from lesson l where l.code='variable-basics';

insert into lesson_block(lesson_id, sequence_no, block_type, content)
select l.id, 2, 'MCQ',
       '{"prompt":"□ + 3 = 8 में खाली जगह पर कौन-सी संख्या आएगी?","options":["3","5","8","11"],"correctOption":"B","feedback":"5 + 3 = 8, इसलिए unknown value 5 है।"}'::jsonb
from lesson l where l.code='variable-basics';

insert into lesson_block(lesson_id, sequence_no, block_type, content)
select l.id, 3, 'AI_HELP',
       '{"title":"समझ नहीं आया?","actions":["EASY_EXPLANATION","EXAMPLE","STEP_BY_STEP","EXAM_ANSWER"],"socratic":true}'::jsonb
from lesson l where l.code='variable-basics';

insert into lesson_block(lesson_id, sequence_no, block_type, content)
select l.id, 4, 'SUMMARY',
       '{"points":["Variable unknown value को represent करता है।","x, y, a जैसे letters variable हो सकते हैं।","Equation में दोनों sides का balance बनाए रखना जरूरी है।"]}'::jsonb
from lesson l where l.code='variable-basics';

insert into question(lesson_id, objective_id, question_type, prompt, explanation, difficulty, sort_order)
select l.id, l.objective_id, 'MCQ',
       'x + 4 = 9 में x की value क्या होगी?',
       'दोनों sides से 4 घटाने पर x = 5 मिलता है।',
       'FOUNDATION', 1
from lesson l where l.code='variable-basics';

insert into question_option(question_id, option_key, label, is_correct, sort_order)
select q.id, v.key, v.label, v.correct, v.ord
from question q
cross join (values
  ('A','3',false,1), ('B','5',true,2), ('C','9',false,3), ('D','13',false,4)
) as v(key,label,correct,ord)
where q.prompt='x + 4 = 9 में x की value क्या होगी?';

insert into question(lesson_id, objective_id, question_type, prompt, explanation, difficulty, sort_order)
select l.id, l.objective_id, 'TRUE_FALSE',
       'Variable की value हमेशा 0 होती है।',
       'गलत। Variable किसी भी allowed number को represent कर सकता है, equation के अनुसार उसकी value तय होती है।',
       'CORE', 2
from lesson l where l.code='variable-basics';

insert into question_option(question_id, option_key, label, is_correct, sort_order)
select q.id, v.key, v.label, v.correct, v.ord
from question q
cross join (values
  ('A','सही',false,1), ('B','गलत',true,2)
) as v(key,label,correct,ord)
where q.prompt='Variable की value हमेशा 0 होती है।';

insert into app_metadata(key, value) values ('schema', 'learning-content-v3')
on conflict (key) do update set value=excluded.value;
