-- V41: private, deduplicated PDF library and subject/chapter resource assignments.
-- PDF bytes remain in PostgreSQL; the student API exposes rendered page images only.
create table learning_pdf_asset (
  id bigint generated by default as identity primary key,
  title varchar(240) not null,
  original_filename varchar(255) not null,
  sha256 varchar(64) not null unique,
  file_size_bytes bigint not null check (file_size_bytes between 1 and 52428800),
  page_count integer not null check (page_count between 1 and 2000),
  pdf_bytes bytea not null,
  source_kind varchar(30) not null default 'ADMIN_UPLOAD'
    check (source_kind in ('ADMIN_UPLOAD','EXTRACTION_IMPORT','LEGACY_IMPORT')),
  source_reference varchar(500),
  created_by_staff_id bigint references staff_account(id) on delete set null,
  created_at timestamptz not null default now(),
  check (length(sha256)=64)
);

create index idx_learning_pdf_asset_created on learning_pdf_asset(created_at desc);
create index idx_learning_pdf_asset_source on learning_pdf_asset(source_kind,created_at desc);

-- A chapter is tied to its actual subject as a database constraint, not just by UI selection.
alter table curriculum_chapter
  add constraint uq_curriculum_chapter_id_subject unique(id,subject_id);

create table learning_document (
  id bigint generated by default as identity primary key,
  pdf_asset_id bigint not null references learning_pdf_asset(id),
  scope varchar(24) not null check (scope in ('SUBJECT_BOOK','CHAPTER_PDF')),
  subject_id bigint not null references curriculum_subject(id),
  chapter_id bigint,
  title varchar(240) not null,
  source_title varchar(300),
  source_url varchar(2000),
  edition varchar(160),
  page_start integer not null default 1 check (page_start >= 1),
  page_end integer not null check (page_end >= page_start),
  status varchar(20) not null default 'DRAFT'
    check (status in ('DRAFT','PUBLISHED','ARCHIVED')),
  version_no integer not null default 1 check (version_no > 0),
  created_by_staff_id bigint references staff_account(id) on delete set null,
  published_by_staff_id bigint references staff_account(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint fk_learning_document_chapter_subject
    foreign key(chapter_id,subject_id)
    references curriculum_chapter(id,subject_id),
  constraint ck_learning_document_scope_chapter
    check (
      (scope='SUBJECT_BOOK' and chapter_id is null)
      or
      (scope='CHAPTER_PDF' and chapter_id is not null)
    )
);

create index idx_learning_document_subject_status
  on learning_document(subject_id,scope,status);
create index idx_learning_document_chapter_status
  on learning_document(chapter_id,status)
  where chapter_id is not null;
create index idx_learning_document_pdf_asset on learning_document(pdf_asset_id);

-- At most one published document is visible in each subject-book or chapter slot.
create unique index uq_learning_document_published_book
  on learning_document(subject_id)
  where scope='SUBJECT_BOOK' and status='PUBLISHED';
create unique index uq_learning_document_published_chapter
  on learning_document(chapter_id)
  where scope='CHAPTER_PDF' and status='PUBLISHED';

create table student_learning_document_progress (
  student_id bigint not null references student(id) on delete cascade,
  learning_document_id bigint not null references learning_document(id) on delete cascade,
  last_page integer not null default 1 check (last_page >= 1),
  last_opened_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(student_id,learning_document_id)
);

create index idx_student_document_progress_updated
  on student_learning_document_progress(student_id,updated_at desc);

insert into app_metadata(key,value)
values ('schema','private-learning-pdf-library-v41')
on conflict(key) do update set value=excluded.value;
