-- V42: durable assessments, immutable attempt snapshots, manual grading and test-level audit.
create table assessment (
  id bigint generated by default as identity primary key,
  title varchar(240) not null,
  description varchar(1200),
  subject_id bigint not null references curriculum_subject(id) on delete restrict,
  chapter_id bigint,
  duration_minutes integer not null default 45 check (duration_minutes between 1 and 240),
  max_attempts integer not null default 1 check (max_attempts between 1 and 10),
  status varchar(20) not null default 'DRAFT'
    check (status in ('DRAFT','PUBLISHED','ARCHIVED')),
  created_by_staff_id bigint references staff_account(id) on delete set null,
  published_by_staff_id bigint references staff_account(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint fk_assessment_chapter_subject
    foreign key(chapter_id,subject_id)
    references curriculum_chapter(id,subject_id)
);
create index idx_assessment_subject_status on assessment(subject_id,status,created_at desc);
create index idx_assessment_chapter_status on assessment(chapter_id,status) where chapter_id is not null;

create table assessment_question (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references assessment(id) on delete cascade,
  source_question_id bigint references question(id) on delete set null,
  sequence_no integer not null check (sequence_no > 0),
  max_marks numeric(8,2) not null default 1 check (max_marks >= 0),
  question_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique(assessment_id,sequence_no)
);
create index idx_assessment_question_assessment on assessment_question(assessment_id,sequence_no);

create table assessment_staff_assignment (
  assessment_id bigint not null references assessment(id) on delete cascade,
  staff_id bigint not null references staff_account(id) on delete restrict,
  assigned_by_staff_id bigint references staff_account(id) on delete set null,
  assigned_at timestamptz not null default now(),
  active boolean not null default true,
  primary key(assessment_id,staff_id)
);
create index idx_assessment_staff_active on assessment_staff_assignment(staff_id,active,assessment_id);

create table student_assessment_attempt (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references assessment(id) on delete restrict,
  student_id bigint not null references student(id) on delete restrict,
  attempt_number integer not null check (attempt_number between 1 and 10),
  status varchar(24) not null default 'IN_PROGRESS'
    check (status in ('IN_PROGRESS','AWAITING_REVIEW','GRADED','RELEASED','ABANDONED')),
  assessment_snapshot jsonb not null,
  started_at timestamptz not null default now(),
  deadline_at timestamptz not null,
  submitted_at timestamptz,
  graded_at timestamptz,
  released_at timestamptz,
  auto_score numeric(10,2) not null default 0 check (auto_score >= 0),
  final_score numeric(10,2) check (final_score >= 0),
  max_score numeric(10,2) not null default 0 check (max_score >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(assessment_id,student_id,attempt_number)
);
create index idx_assessment_attempt_student on student_assessment_attempt(student_id,created_at desc);
create index idx_assessment_attempt_queue on student_assessment_attempt(status,submitted_at desc)
  where status in ('AWAITING_REVIEW','GRADED');
create unique index uq_assessment_attempt_in_progress
  on student_assessment_attempt(assessment_id,student_id)
  where status='IN_PROGRESS';

create table student_assessment_attempt_question (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references student_assessment_attempt(id) on delete restrict,
  source_assessment_question_id bigint references assessment_question(id) on delete set null,
  source_question_id bigint references question(id) on delete set null,
  sequence_no integer not null check (sequence_no > 0),
  max_marks numeric(8,2) not null check (max_marks >= 0),
  question_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique(attempt_id,sequence_no)
);
create index idx_attempt_question_attempt on student_assessment_attempt_question(attempt_id,sequence_no);

create table student_assessment_answer (
  id bigint generated by default as identity primary key,
  attempt_question_id bigint not null unique
    references student_assessment_attempt_question(id) on delete restrict,
  response_payload jsonb not null default '""'::jsonb,
  answer_status varchar(24) not null default 'NOT_ANSWERED'
    check (answer_status in ('NOT_ANSWERED','AUTO_GRADED','PENDING_REVIEW','GRADED')),
  is_correct boolean,
  awarded_marks numeric(8,2) check (awarded_marks >= 0),
  teacher_feedback varchar(2000),
  saved_at timestamptz not null default now(),
  graded_at timestamptz,
  graded_by_staff_id bigint references staff_account(id) on delete set null,
  check (teacher_feedback is null or length(teacher_feedback) <= 2000)
);
create index idx_assessment_answer_review on student_assessment_answer(answer_status,attempt_question_id)
  where answer_status='PENDING_REVIEW';

-- One row per meaningful test/attempt action. Never record one audit row per question.
create table assessment_audit_log (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references assessment(id) on delete restrict,
  attempt_id bigint references student_assessment_attempt(id) on delete restrict,
  actor_staff_id bigint references staff_account(id) on delete set null,
  actor_student_id bigint references student(id) on delete set null,
  actor_role varchar(32) not null,
  action varchar(48) not null,
  previous_status varchar(24),
  new_status varchar(24),
  note varchar(1200),
  occurred_at timestamptz not null default now()
);
create index idx_assessment_audit_test_time on assessment_audit_log(assessment_id,occurred_at desc,id desc);
create index idx_assessment_audit_attempt_time on assessment_audit_log(attempt_id,occurred_at desc)
  where attempt_id is not null;

insert into staff_permission_catalog(permission_key,display_name,description)
values ('ASSESSMENT_GRADE','Grade student assessments','Review submitted test answers, assign marks, and release final results for assessments assigned to you.')
on conflict(permission_key) do update
set display_name=excluded.display_name,description=excluded.description;

insert into app_metadata(key,value)
values ('schema','durable-assessment-attempts-v42')
on conflict(key) do update set value=excluded.value;
