-- V43: scheduled live classes, private recordings, attendance, and playback progress.
create table learning_class_session (
  id bigint generated by default as identity primary key,
  title varchar(240) not null,
  description varchar(1600),
  subject_id bigint not null references curriculum_subject(id) on delete restrict,
  chapter_id bigint,
  provider varchar(32) not null default 'CUSTOM'
    check (provider in ('CUSTOM','GOOGLE_MEET','ZOOM','MICROSOFT_TEAMS','OTHER')),
  private_join_url varchar(2000) not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status varchar(20) not null default 'SCHEDULED'
    check (status in ('SCHEDULED','LIVE','COMPLETED','CANCELLED')),
  host_staff_id bigint references staff_account(id) on delete set null,
  created_by_staff_id bigint references staff_account(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fk_learning_class_session_chapter_subject
    foreign key(chapter_id,subject_id)
    references curriculum_chapter(id,subject_id),
  check (ends_at > starts_at)
);
create index idx_learning_class_session_subject_time
  on learning_class_session(subject_id,starts_at,status);
create index idx_learning_class_session_chapter
  on learning_class_session(chapter_id,starts_at)
  where chapter_id is not null;
create index idx_learning_class_session_host_time
  on learning_class_session(host_staff_id,starts_at desc)
  where host_staff_id is not null;

create table recorded_class (
  id bigint generated by default as identity primary key,
  title varchar(240) not null,
  description varchar(1600),
  subject_id bigint not null references curriculum_subject(id) on delete restrict,
  chapter_id bigint,
  class_session_id bigint references learning_class_session(id) on delete set null,
  storage_key varchar(120) not null unique,
  original_filename varchar(255) not null,
  media_type varchar(80) not null
    check (media_type in ('video/mp4','video/webm','video/quicktime')),
  file_size_bytes bigint not null check (file_size_bytes between 1 and 524288000),
  sha256 varchar(64) not null,
  duration_seconds integer check (duration_seconds is null or duration_seconds between 1 and 86400),
  status varchar(20) not null default 'DRAFT'
    check (status in ('DRAFT','PUBLISHED','ARCHIVED')),
  created_by_staff_id bigint references staff_account(id) on delete set null,
  published_by_staff_id bigint references staff_account(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint fk_recorded_class_chapter_subject
    foreign key(chapter_id,subject_id)
    references curriculum_chapter(id,subject_id),
  check (length(sha256)=64)
);
create index idx_recorded_class_subject_status
  on recorded_class(subject_id,status,created_at desc);
create index idx_recorded_class_chapter_status
  on recorded_class(chapter_id,status)
  where chapter_id is not null;
create index idx_recorded_class_session
  on recorded_class(class_session_id)
  where class_session_id is not null;

create table learning_class_attendance (
  session_id bigint not null references learning_class_session(id) on delete restrict,
  student_id bigint not null references student(id) on delete restrict,
  first_joined_at timestamptz not null default now(),
  last_joined_at timestamptz not null default now(),
  last_left_at timestamptz,
  active_since_at timestamptz,
  join_count integer not null default 0 check (join_count >= 0),
  total_seconds bigint not null default 0 check (total_seconds >= 0),
  updated_at timestamptz not null default now(),
  primary key(session_id,student_id)
);
create index idx_learning_class_attendance_student
  on learning_class_attendance(student_id,last_joined_at desc);

create table student_recorded_class_progress (
  student_id bigint not null references student(id) on delete restrict,
  recorded_class_id bigint not null references recorded_class(id) on delete restrict,
  last_position_seconds integer not null default 0 check (last_position_seconds >= 0),
  watched_seconds bigint not null default 0 check (watched_seconds >= 0),
  completed boolean not null default false,
  last_played_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(student_id,recorded_class_id)
);
create index idx_recorded_class_progress_student
  on student_recorded_class_progress(student_id,updated_at desc);

insert into staff_permission_catalog(permission_key,display_name,description)
values ('CLASS_MANAGE','Manage live and recorded classes','Schedule live classes, manage private meeting links, upload recordings, and publish class access.')
on conflict(permission_key) do update
set display_name=excluded.display_name,description=excluded.description;

insert into app_metadata(key,value)
values ('schema','live-and-recorded-classes-v43')
on conflict(key) do update set value=excluded.value;
