-- V44: connect existing source records to stored PDFs and provide an admin-reviewed ingestion pipeline.
-- Existing library assets stay approved; newly downloaded/split assets remain hidden until review.
alter table learning_pdf_asset
  add column if not exists review_status varchar(20) not null default 'APPROVED',
  add column if not exists source_content_id bigint references content_source(id) on delete set null,
  add column if not exists reviewed_by_staff_id bigint references staff_account(id) on delete set null,
  add column if not exists reviewed_at timestamptz;

alter table learning_pdf_asset drop constraint if exists learning_pdf_asset_source_kind_check;
alter table learning_pdf_asset add constraint learning_pdf_asset_source_kind_check
  check (source_kind in ('ADMIN_UPLOAD','EXTRACTION_IMPORT','LEGACY_IMPORT','SOURCE_INGESTION'));

do $asset_review_status$
begin
  if not exists (select 1 from pg_constraint where conname='learning_pdf_asset_review_status_check') then
    alter table learning_pdf_asset add constraint learning_pdf_asset_review_status_check
      check (review_status in ('DRAFT','REVIEW','APPROVED','REJECTED'));
  end if;
end $asset_review_status$;

alter table content_source
  add column if not exists learning_pdf_asset_id bigint references learning_pdf_asset(id) on delete set null;

-- Recover links wherever the source registry already has a SHA-256 or a source reference.
update content_source cs
set learning_pdf_asset_id=a.id
from learning_pdf_asset a
where cs.learning_pdf_asset_id is null
  and (lower(coalesce(cs.checksum,''))=lower(a.sha256)
       or (cs.source_url is not null and cs.source_url=a.source_reference));

create index if not exists idx_learning_pdf_asset_review_status
  on learning_pdf_asset(review_status,created_at desc);
create index if not exists idx_content_source_pdf_asset
  on content_source(learning_pdf_asset_id);

create table source_ingestion_job (
  id bigint generated by default as identity primary key,
  source_id bigint not null references content_source(id) on delete restrict,
  subject_id bigint not null references curriculum_subject(id) on delete restrict,
  source_title varchar(300) not null,
  source_url text not null,
  final_pdf_url text,
  edition varchar(160) not null default 'UNVERIFIED',
  language varchar(20) not null default 'hi',
  book_asset_id bigint references learning_pdf_asset(id) on delete restrict,
  page_count integer check (page_count between 1 and 2000),
  detected_outline jsonb not null default '[]'::jsonb,
  status varchar(24) not null default 'DOWNLOADING'
    check (status in ('DOWNLOADING','REVIEW','APPROVED','REJECTED','FAILED')),
  error_message varchar(1200),
  created_by_staff_id bigint references staff_account(id) on delete set null,
  reviewed_by_staff_id bigint references staff_account(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index idx_source_ingestion_job_status on source_ingestion_job(status,updated_at desc);
create index idx_source_ingestion_job_source on source_ingestion_job(source_id,created_at desc);

create table source_ingestion_chapter (
  id bigint generated by default as identity primary key,
  job_id bigint not null references source_ingestion_job(id) on delete cascade,
  chapter_id bigint not null references curriculum_chapter(id) on delete restrict,
  chapter_title varchar(300) not null,
  page_start integer not null check (page_start >= 1),
  page_end integer not null check (page_end >= page_start),
  pdf_asset_id bigint references learning_pdf_asset(id) on delete restrict,
  learning_document_id bigint references learning_document(id) on delete set null,
  status varchar(20) not null default 'NEEDS_REVIEW'
    check (status in ('NEEDS_REVIEW','APPROVED','REJECTED')),
  review_notes varchar(1200),
  reviewed_by_staff_id bigint references staff_account(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique(job_id,chapter_id)
);

create index idx_source_ingestion_chapter_job_status
  on source_ingestion_chapter(job_id,status,id);

insert into app_metadata(key,value)
values ('schema','reviewed-source-pdf-ingestion-v44')
on conflict(key) do update set value=excluded.value;
