create table student (
  id bigint generated by default as identity primary key,
  public_id uuid not null unique,
  display_name varchar(120) not null,
  class_code varchar(30) not null references curriculum_class(code),
  board varchar(80) not null,
  language varchar(20) not null default 'hi',
  environment varchar(30) not null default 'PRODUCTION',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (environment in ('LOCAL_PREVIEW','PRODUCTION'))
);

create table student_lesson_progress (
  id bigint generated by default as identity primary key,
  student_id bigint not null references student(id) on delete cascade,
  lesson_id bigint not null references lesson(id) on delete cascade,
  status varchar(30) not null default 'NOT_STARTED',
  progress_percent integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  last_opened_at timestamptz,
  unique(student_id,lesson_id),
  check (status in ('NOT_STARTED','IN_PROGRESS','COMPLETED')),
  check (progress_percent between 0 and 100)
);

create table student_question_attempt (
  id bigint generated by default as identity primary key,
  student_id bigint not null references student(id) on delete cascade,
  question_id bigint not null references question(id) on delete cascade,
  selected_option varchar(20) not null,
  correct boolean not null,
  answered_at timestamptz not null default now()
);

create table learning_session (
  id bigint generated by default as identity primary key,
  student_id bigint not null references student(id) on delete cascade,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  minutes integer not null default 0,
  source varchar(40) not null default 'LESSON',
  check (minutes between 0 and 240)
);

create index idx_student_progress_student on student_lesson_progress(student_id,status);
create index idx_student_attempt_student on student_question_attempt(student_id,answered_at);
create index idx_learning_session_student on learning_session(student_id,started_at);

insert into app_metadata(key,value) values ('schema','student-progress-v5')
on conflict(key) do update set value=excluded.value;