-- V9: market-ready learning/content coverage model.
-- This migration deliberately separates source coverage from QuantaEdge-authored pedagogy.
-- Nothing is promoted to SOURCE_BACKED merely because a lesson shell exists.

alter table question add column if not exists source_kind varchar(40) not null default 'AUTHOR_CREATED';
alter table question add column if not exists source_title varchar(300);
alter table question add column if not exists source_ref varchar(200);
alter table question add column if not exists source_year integer;
alter table question add column if not exists board varchar(100);
alter table question add column if not exists marks integer;
alter table question add column if not exists exam_format varchar(60);
alter table question add column if not exists topic varchar(200);
alter table question add column if not exists subtopic varchar(200);
alter table question add column if not exists skill varchar(80);
alter table question add column if not exists tags jsonb not null default '[]'::jsonb;

alter table question drop constraint if exists question_question_type_check;
alter table question add constraint question_question_type_check check (
  question_type in (
    'MCQ','TRUE_FALSE','INPUT','MATCH','ORDER','ASSERTION_REASON',
    'CASE_BASED','SHORT_ANSWER','LONG_ANSWER','NUMERICAL',
    'DIAGRAM','MAP','SOURCE_BASED'
  )
);

create table if not exists content_source (
  id bigint generated by default as identity primary key,
  source_kind varchar(40) not null,
  title varchar(300) not null,
  provider varchar(200) not null,
  source_url varchar(1000),
  edition varchar(120),
  language varchar(40) not null default 'hi',
  source_year integer,
  accessed_at timestamptz not null default now(),
  checksum varchar(128),
  status varchar(30) not null default 'REFERENCE',
  unique(source_kind,title,edition)
);

create table if not exists chapter_source (
  chapter_id bigint not null references curriculum_chapter(id) on delete cascade,
  source_id bigint not null references content_source(id) on delete cascade,
  source_chapter_no integer,
  source_chapter_title varchar(300),
  source_locator varchar(300),
  coverage_type varchar(40) not null default 'CURRICULUM',
  coverage_status varchar(30) not null default 'MAPPED',
  notes text,
  primary key(chapter_id,source_id,coverage_type)
);

create table if not exists chapter_concept (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references curriculum_chapter(id) on delete cascade,
  code varchar(100) not null,
  title varchar(300) not null,
  description text,
  prerequisite_codes jsonb not null default '[]'::jsonb,
  concept_order integer not null default 0,
  source_refs jsonb not null default '[]'::jsonb,
  status varchar(30) not null default 'AUTHORING_REQUIRED',
  unique(chapter_id,code)
);

create table if not exists lesson_requirement (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references curriculum_chapter(id) on delete cascade,
  requirement_code varchar(80) not null,
  required boolean not null default true,
  min_count integer not null default 1,
  description varchar(500) not null,
  unique(chapter_id,requirement_code)
);

create table if not exists question_source_tag (
  id bigint generated by default as identity primary key,
  question_id bigint not null references question(id) on delete cascade,
  tag varchar(100) not null,
  unique(question_id,tag)
);

insert into content_source(source_kind,title,provider,source_url,edition,language,status)
values
 ('STATE_TEXTBOOK','Bihar SCERT Class 6 Mathematics — गणित भाग-6','SCERT Bihar','https://scert.bihar.gov.in/eresources/गणित-भाग-6-1707973215','current','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 7 Mathematics — गणित भाग-7','SCERT Bihar','https://scert.bihar.gov.in/eresources/गणित-भाग-7-1708060463','current','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 8 Mathematics — गणित भाग-8','SCERT Bihar','https://scert.bihar.gov.in/eresources/गणित-भाग-8-1708403831','current','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 6 Science — विज्ञान भाग-1','SCERT Bihar','https://scert.bihar.gov.in/eresources/विज्ञान-भाग-1-1707973674','current','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 7 Science — विज्ञान भाग-2','SCERT Bihar','https://scert.bihar.gov.in/eresources/विज्ञान-भाग-2-1708062711','current','hi','REFERENCE'),
 ('STATE_TEXTBOOK','Bihar SCERT Class 8 Science — विज्ञान भाग-3','SCERT Bihar','https://scert.bihar.gov.in/eresources/विज्ञान-भाग-3-1708404249','current','hi','REFERENCE'),
 ('TEACHER_GUIDE','SCERT Bihar Mathematics Teacher Handbook Classes 6–8','SCERT Bihar','https://scert.bihar.gov.in/eresources/mathematics-handbook-for-teachers-1753723347','current','hi','REFERENCE'),
 ('TEACHER_GUIDE','SCERT Bihar Science Teacher Handbook Classes 6–8','SCERT Bihar','https://scert.bihar.gov.in/eresources/science-handbook-for-teachers-class-6-8-1753723306','current','hi','REFERENCE'),
 ('NCERT_CATALOGUE','NCERT Textbooks I–XII','NCERT','https://ncert.nic.in/textbook.php','current','hi','REFERENCE')
on conflict(source_kind,title,edition) do update set source_url=excluded.source_url,provider=excluded.provider,status='REFERENCE';

-- Every canonical chapter gets an explicit audit contract.
insert into lesson_requirement(chapter_id,requirement_code,required,min_count,description)
select ch.id, v.code, true, v.min_count, v.description
from curriculum_chapter ch
join curriculum_subject s on s.id=ch.subject_id
join curriculum_class c on c.id=s.class_id
cross join (values
 ('PREREQUISITE',1,'पूर्व ज्ञान जाँच'),
 ('EXPLANATION',1,'स्पष्ट हिन्दी में अवधारणा व्याख्या'),
 ('WORKED_EXAMPLE',1,'शिक्षक-शैली worked example'),
 ('GUIDED_PRACTICE',1,'Guided practice'),
 ('INDEPENDENT_PRACTICE',1,'Independent practice'),
 ('RECAP',1,'Chapter recap'),
 ('VISUAL_OR_NOT_REQUIRED',1,'Visual decision recorded'),
 ('NCERT_OR_TEXTBOOK_MAPPING',1,'NCERT/SCERT textbook mapping'),
 ('BOARD_FORMAT_COVERAGE',1,'Board-format question coverage'),
 ('SOURCE_TAGGED_QUESTIONS',1,'Source/year/format tagged questions')
) v(code,min_count,description)
where c.code in ('6','7','8') and s.code in ('maths','science') and ch.active=true
on conflict(chapter_id,requirement_code) do update set
 required=excluded.required,min_count=excluded.min_count,description=excluded.description;

-- Existing V8 generic lesson shells are intentionally not treated as proof of
-- source-backed completeness. Their content remains visible for local UX QA,
-- but the audit distinguishes shell coverage from authored/source-backed coverage.
insert into app_metadata(key,value)
values ('schema','market-ready-learning-coverage-v9')
on conflict(key) do update set value=excluded.value;

alter table lesson_block drop constraint if exists lesson_block_block_type_check;
alter table lesson_block add constraint lesson_block_block_type_check check (block_type in (
  'EXPLANATION','IMAGE','DIAGRAM','VIDEO','QUESTION','MCQ','TRUE_FALSE','MATCH','ORDER','INPUT',
  'HINT','AI_HELP','SUMMARY','CHALLENGE','PREREQUISITE','WORKED_EXAMPLE','GUIDED_PRACTICE',
  'INDEPENDENT_PRACTICE','RECAP'
));
